Repository health-connector/enroll, pull requests merged in 2018-07, with the labels that each got.

#922 21364: fix this cucumber from flickering
  features/brokers/create_broker_agency_profiles_individual_disabled.feature
  features/step_definitions/brokers_steps.rb
  features/step_definitions/integration_steps.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Stakeholder Review, Tracker: Enhancement

#1303 26065: Refactor Cobra Enrollment
  script/cobra_enrollment_report.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Feature

#1306 25983: Refactor Minimum Participation Report
  lib/tasks/employers_failing_minimum_participation.rake
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Feature

#1292 26064: Refactor - oustanding shop policies to pull
  app/models/queries/policy_aggregation_pipeline.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Pending Deployment, Tracker: Feature

#1312 26709: Unable to generate V2 XML.
  app/data_migrations/components/fix_employer_attestation.rb
  lib/tasks/migrations/components/fix_employer_attestation.rake
  spec/data_migrations/components/fix_employer_attestation_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Pending Deployment, Tracker: Bug

#1313 26507: POC Report Research
  lib/tasks/hbx_reports/employer_poc_pending_report.rake
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Support

#1322 26697: EE Receives Error Message - HBX 108941
  db/migrate/20180430172054_extract_county_zips_for_ma.rb
  db/migrate/20180430181820_extract_rating_areas_for_ma.rb
  db/migrate/20180503145357_cca_carrier_profiles_migration.rb
  db/migrate/20180515171830_migrate_ma_service_areas.rb
  db/migrate/20180515181450_generate_benefit_market_catalogs.rb
  db/migrate/20180718162736_update_ma_list_bill_pricing_model.rb
  db/seedfiles/cca/fixtures/pricing_model_5b044e499f880b5d6f36c788.yaml
Labels: Mergeable: Yes, Priority: Immediate, Status: Pending Deployment, Tracker: Critical Data

#1310 26190: MYC ER Account Creation Error
  script/set_bs_employer_profile_id_on_staff_role.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1307 25799: SIC code selection issue
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/registrations/_sic_help.html.erb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1308 25924: Families tab is not actionable - BQT
  app/views/shared/engines/_broker_menu.html.erb
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Bug

#1309 26019: DOB Formatting issue with ER screener page
  app/views/ui-components/v1/forms/broker_registration/_personal_information.html.slim
  app/views/ui-components/v1/forms/employer_registration/_staff_role_information.html.slim
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#1320 26760: Broker Applied but Application Not Showing in EA
  script/26760_migrate_brokers_to_new_model.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#1338 27106: Update MAE069 notice trigger to New Model
  components/benefit_sponsors/app/models/benefit_sponsors/model_events/hbx_enrollment.rb
  components/benefit_sponsors/app/models/benefit_sponsors/observers/hbx_enrollment_observer.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Code Refactor

#1341 27156: Refactor Ticket - MAE081 - Notify EE of DPT Termination due to age-off
  lib/tasks/recurring/employee_dependent_age_off_termination.rake
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#1321 25955: MYC Notices - MPI Code on Cover Page is printing too high
  components/notifier/app/models/notifier/notice_builder.rb
  components/notifier/app/views/layouts/notifier/pdf_layout.html.erb
Labels: Mergeable: Yes, Priority: High, Status: Pending Deployment, Tracker: Bug

#1315 26764: Update Outstanding Enrollments Report for New Model
  lib/tasks/hbx_reports/outstanding_monthly_enrollments.rake
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1302 26022: PY is Locked after looking at SBCs link from "View Summary"
  app/views/ui-components/v1/cards/_metal_level_select.html.slim
Labels: Mergeable: Yes, Priority: Urgent, Status: Pending Deployment, Tracker: Bug

#1353 27448: Repoint POC to New Model ER
  script/fix_staff_role_reference_to_new_model_profile.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Pending Deployment, Tracker: Critical Data

#1363 27481: Refactor - Load Rate Reference
  lib/tasks/migrations/load_rate_reference.rake
  spec/lib/migrations/load_rate_reference_spec.rb
  spec/lib/tasks/migrations/load_rate_reference_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Peer Review, Tracker: Code Refactor

#1296 26045: Renewal Draft PY - when editing, submit button is disabled until the contributions are changed
  app/views/ui-components/v1/cards/_metal_level_select.html.slim
Labels: Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#1304 25768: when we edit draft plan year, it should be displayed as "Save Plan Year"
  app/views/ui-components/v1/cards/_metal_level_select.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/_edit.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/edit.html.slim
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1325 26721: Shop Enrollment Recon Report Update
  script/update_person_record_family.rb
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Bug

#1364 27563: Investigate Initial Group Transmissions
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1340 26771: Update the rake to modify on Organization instance
  app/data_migrations/components/fix_organization.rb
  lib/tasks/migrations/components/fix_organization.rake
  spec/data_migrations/components/fix_organization_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1373 25286: Error in ER Plan Year Tile
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_sponsored_benefit.html.erb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug
