Repository health-connector/enroll, pull requests merged in 2018-04, with the labels that each got.

#1099 23511: Update is_vertical and is_horizontal fields in Plan Model for DC plans
  app/data_migrations/update_all_plan_options.rb
  lib/tasks/update_plan_offerings_at_carrier_level.rake
  spec/data_migrations/update_all_plan_options_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1101 23491: Enable DC colors for buttons and "config" page
  app/assets/stylesheets/_variables.scss.erb
  app/assets/stylesheets/modules.scss.erb
  config/settings.yml
  vendor/assets/stylesheets/bootstrap.css.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1104 23514: Issues with Broker selection
  components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_organization.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1105 23448: On consumer Documents view is not displaying properly
  app/assets/stylesheets/modules.scss.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1106 23554: Populate plan premium tables
  lib/object_builders/qhp_rate_builder.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1107 23520: Enroll as individual button missing for new registration employee
  app/views/insured/employee_roles/_select_employer.html.haml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1108 23522: IVL market should not have 14 day rule when terminating policy.
  app/views/insured/group_selection/terminate_confirm.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1096 23507: Carrier Logos are missing.
  app/assets/images/logo/carrier/aetna.jpg
  app/assets/images/logo/carrier/bestlife.jpg
  app/assets/images/logo/carrier/carefirst.jpg
  app/assets/images/logo/carrier/delta_dental.jpg
  app/assets/images/logo/carrier/dentegra.jpg
  app/assets/images/logo/carrier/dominion.jpg
  app/assets/images/logo/carrier/kaiser.jpg
  app/assets/images/logo/carrier/metlife.jpg
  app/assets/images/logo/carrier/oci.jpg
  app/assets/images/logo/carrier/uhcma.jpg
  app/assets/images/logo/carrier/uhic.jpg
Labels: Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1110 23572: Text changes under Employer Plan selection
  app/assets/javascripts/employer_profile.js.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1070 23413: Move employer monthly transmission settings into concerns
  app/models/concerns/config/aca_model_concern.rb
  app/models/employer_profile.rb
  spec/models/concerns/config/aca_model_concern_spec.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Hot Fix

#1100 23495: "View Username and Email" button does not work for admin
  app/models/effective/datatables/employer_datatable.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1113 23468: when broker click "employers" button should see general agency selection section
  app/views/shared/engines/_broker_menu.html.erb
  components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/broker_agency_profiles_controller.rb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/broker_agency_profiles/_employers.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1114 23575: Issues with Dental Plans-Benefit package
  app/assets/javascripts/plan_year_selection.js.erb
  app/views/employers/plan_years/calc_offered_plan_contributions.js.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1118 23470: Broker page should disable "Add Prospect Employer" button
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/broker_agency_profiles/_employers.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1115 23585: Text & Color changes - IVL/EE account
  app/assets/stylesheets/_variables.scss.erb
  app/assets/stylesheets/insured.scss.erb
  app/assets/stylesheets/text_styles.scss.erb
  app/views/insured/families/_qle_detail.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1116 23522: IVL market should not have 14 day rule when terminating policy.
  app/views/insured/group_selection/terminate_confirm.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1120 23592: 500 error when admin clicked on call hub on documents tab.
  config/routes.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1123 23582: Logo issue & Title color for QLE carousel.
  app/assets/images/icons/shop_for_plan.png
  app/assets/stylesheets/_variables.scss.erb
  app/assets/stylesheets/custom.scss.erb
  config/settings.yml
Labels: Mergeable: No, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1124 23476: Outstanding verification's link under Families tab
  app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1125 23622: Admin actions - Add SEP, Edit DOB/SSN, View Username and Email should be disabled under Families tab in MA
  app/models/effective/datatables/family_data_table.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1126 23622: Admin actions - Add SEP, View Username and Email should be disabled under Families tab in MA
  app/models/effective/datatables/family_data_table.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1080 23027: Information updates not saving under MA Broker Agency account
  app/controllers/broker_agencies/profiles_controller.rb
  spec/controllers/broker_agencies/profiles_controller_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1129 23622: Admin actions - Add SEP, View Username and Email should be disabled under Families tab in MA
  app/models/effective/datatables/family_data_table.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1128 23603: DC PVT - IVL and EE - Network and Deductible Alignment issues
  app/views/insured/plan_shoppings/_plan_details.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1131 23092: MA Logo, MA Admin Tool Format, Colors
  app/helpers/portal_header_helper.rb
  db/seedfiles/translations/en/welcome_index.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1132 23644: Employee Account creation-Top nav showing incorrect text
  app/assets/images/icons/dc-icon-individual.png
  app/helpers/application_helper.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1133 23621: Plans not loading when Employer add multiple benefit groups
  app/assets/javascripts/plan_year_selection.js.erb
  app/controllers/employers/plan_years_controller.rb
  app/views/employers/plan_years/generate_health_carriers_and_plans.js.erb
  app/views/shared/_reference_plans_list.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#712 19187: ER Per-Member Premium Display
  app/views/employers/census_employees/_enrollment_details.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1136 23641: We are sorry error on creating plan year with meta level plans
  app/models/benefit_group.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1098 23532: New hire coverage policy should apply on 6/1 conversion employer
  app/models/importers/conversion_employer_plan_year.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1035 21940: MA Refactor ticket #17746 - MAG049
  app/helpers/application_helper.rb
  app/models/employer_profile.rb
  app/notices/shop_employer_notices/employer_broker_fired_notice.rb
  app/views/notices/shop_employer_notices/employer_broker_fired_notice.html.erb
  components/notifier/app/models/notifier/builders/broker.rb
  components/notifier/app/models/notifier/builders/employer_profile.rb
  components/notifier/app/models/notifier/merge_data_models/broker.rb
  db/seedfiles/notice_triggers_seed.rb
  spec/models/employer_profile_spec.rb
  spec/models/model_events/broker_fired_confirmation_to_employer_spec.rb
  spec/notices/shop_employer_notices/employer_broker_fired_notice_spec.rb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1138 23689: IVL Verifications: Wrong test shown when clicked on Documents FAQ button in Documents Page for Consumer
  app/views/insured/families/verification/_documents_verification_list.en.html.erb
  app/views/insured/families/verification/_documents_verification_list.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1142 23661: Generated Incorrect Employer Invoice
  app/assets/images/dc_invoice_logo.png
  app/invoices/invoice_helper.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1140 23641: We are sorry error on creating plan year with meta level plans
  app/models/plan.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1022 22857: Add new resources to Application Event Mapper in Notice Engine
  app/models/observers/observer.rb
  components/notifier/app/models/notifier/application_event_mapper.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: Normal, Status: Promote to UAT, Tracker: Bug

#1026 21935: MA Refactor ticket #17521
  app/controllers/insured/employee_roles_controller.rb
  app/notices/shop_employee_notices/employee_matches_employer_rooster_notice.rb
  app/views/notices/shop_employee_notices/employee_matches_employer_rooster_notification.html.erb
  db/seedfiles/notice_triggers_seed.rb
  spec/controllers/insured/employee_roles_controller_spec.rb
  spec/models/model_events/employee_matches_employer_rooster_notice_spec.rb
  spec/notices/shop_employee_notices/employee_matches_employer_rooster_notice_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1143 23692: We are sorry error with Employee roster template upload
  app/views/employers/employer_profiles/_download_new_template.html.erb
  app/views/employers/employer_profiles/_upload_employees.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1149 23691: NO Group Files Dropping in DC PVT
  app/models/observers/observer.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1148 23561: Issue on Employer account
  app/helpers/config/aca_helper.rb
  app/helpers/config/site_helper.rb
  app/views/employers/employer_profiles/my_account/_broker_agency.html.erb
  app/views/shared/_benefit_group_fields.html.erb
  app/views/shared/_plan_year_fields.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1150 23639: Dental Benefits Tab showing up without selecting under Plan year page
  app/views/employers/plan_years/calc_offered_plan_contributions.js.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1152 23621: Plans not loading when Employer add multiple benefit groups
  app/views/shared/_reference_plans_list.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1153 23661: Generated Incorrect Employer Invoice
  app/invoices/employer_invoice.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1154 23561: Issue on Employer account
  app/views/shared/_benefit_group_fields.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1135 23626: Binder paid status is being set without invoking state transition
  app/models/employer_profile.rb
  spec/models/employer_profile_spec.rb
Labels: Priority: High, Status: Accepted Pending Release, Tracker: Bug

#971 21889: MA Refactor ticket #17093 - MIG022
  app/invoices/employer_invoice.rb
  app/notices/shop_employer_notices/initial_employer_invoice_available.rb
  app/views/notices/shop_employer_notices/initial_employer_invoice_available_notice.html.erb
  db/seedfiles/notice_triggers_seed.rb
  spec/invoices/employer_invoice_spec.rb
  spec/notices/shop_employer_notices/initial_employer_invoice_available_spec.rb
Labels: Mergeable: No, Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1158 23812: Life event logo not rendering
  app/assets/images/icons/dc-life-event.png
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1157 23681: TUFTS Direct - 6/1 Conversion Data Load
  app/models/importers/mhc/conversion_employer_plan_year.rb
Labels: Priority: Immediate, Status: Accepted Pending Release, Tracker: Feature

#1172 23918: Font change in PVT
  app/assets/stylesheets/_variables.scss.erb
  app/assets/stylesheets/custom.scss.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1173 23890: Error on consumers account after adding SEP
  app/views/insured/families/_qle_detail_for_existing_sep.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1176 23537: Communication Preferences Doubled
  app/views/employers/employer_profiles/_employer_form.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: In Progress, Tracker: Bug

#1087 23439: Bug Ticket - Plan Year is Moving to Enroll State Instead of Application Ineligible
  app/models/census_employee.rb
  app/models/plan_year.rb
  spec/models/census_employee_spec.rb
  spec/models/plan_year_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1175 23787: Incomplete SEP pop-up message
  app/views/insured/families/_shop_for_plans_widget.html.erb
  db/seedfiles/translations/en/insured.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1182 24045: Binder Payment Deadline - 5/1 Initial Groups
  app/models/plan_year.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Data

#1014 22172: User Name Change Rake
  app/data_migrations/change_username.rb
  spec/data_migrations/change_username_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1191 24030: Temporary ER Shopping Start_on Configuration Change
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
  spec/models/general_agency_profile_spec.rb
  spec/models/model_events/renewal_employer_reminder_to_publish_plan_year_spec.rb
  spec/rails_helper.rb
  spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Support
