Repository health-connector/enroll, pull requests merged in 2018-08, with the labels that each got.

#1371 25273: Admin - Employer - Datable Issues
  app/assets/stylesheets/ui-components/mahc-theme.scss
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug

#1378 25808: Dates are not displaying on reload and question mark helper missing
  app/helpers/config/site_helper.rb
  components/benefit_sponsors/app/helpers/benefit_sponsors/application_helper.rb
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim
Labels: Priority: High, Status: Pending Deployment, Tracker: Bug

#1381 25420: Employer Account Creation Page Help Text
  app/views/ui-components/v1/forms/employer_registration/_employer_profile_form.html.slim
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug

#1382 25186: Benefit Package - Select Your Plan Offering - Select Your Reference Plan - UI defects
  app/assets/stylesheets/ui-components/mahc-theme.scss
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug

#1369 25366: Revert Plan Year Button is not Aligned
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug

#920 18741: Repeated flash messages
  app/views/devise/passwords/create.js.erb
Labels: Priority: Normal, Status: Dev Review, Tracker: Bug

#1368 25305: Admin - Families - Text Alignment Issue
  app/views/exchanges/hbx_profiles/_family_index_datatable.html.slim
  project_gems/effective_datatables-2.6.14/app/assets/stylesheets/dataTables/dataTables.bootstrap.css
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1385 25935: Error message is different when "Plan Year failed to publish.
  components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1392 25621: Broker UI Issues
  app/views/shared/brokers/_applicant.html.erb
  app/views/shared/brokers/_broker_fields.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Stakeholder Review, Tracker: Bug

#1394 28071: Broker Commissions Statements - No Clickable Links to Open/View/Download the Statements in MA Prod
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_commission_statements.html.erb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1390 25462: ER Add/Edit Plan Year & Document Upload - Missing Question mark and hover-over help text
  app/views/ui-components/v1/cards/_sponsor_contributions.html.slim
  app/views/ui-components/v1/cards/_sponsor_contributions_shell.html.slim
  components/benefit_sponsors/app/helpers/benefit_sponsors/application_helper.rb
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim
Labels: Mergeable: No, Priority: Normal, Status: Dev Review, Tracker: Bug

#1357 25929: Duplicate Invoice Availability Message in ER Account after Invoice Generation in PVT 2
  components/notifier/app/models/notifier/notice_builder.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1398 25527: Admin Employer List Page - Employer filters and Attesation document alignment
  app/views/employers/employer_attestations/_edit.html.erb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1408 25989: EE Plan Shopping - Plan List - Wrong Default Sort Order (Should be Premium Lowest to Highest)
  app/controllers/insured/plan_shoppings_controller.rb
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Bug

#1415 25809: Contributions Dont Store When Changing Plan Type
  app/views/ui-components/v1/cards/_metal_level_select.html.slim
Labels: Priority: High, Status: Pending Deployment, Tracker: Bug

#1417 25976: Network Notes - Help Icon text Issue
  app/views/ui-components/v1/cards/_metal_level_select.html.slim
Labels: Mergeable: Yes, Priority: Normal, Status: Stakeholder Review, Tracker: Bug

#1425 25946: Binder Paid Filter is not working
  components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_datatable_concern.rb
Labels: Priority: High, Tracker: Bug

#1426 28172: Error message received when selecting user account-Benjamin Day(129021)
  app/data_migrations/update_employee_role_id.rb
  lib/tasks/migrations/update_employee_role_id.rake
  spec/data_migrations/update_employee_role_id_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1431 28869: Fix the Census Employee id on the Employee Role
  app/data_migrations/update_employer_profile_id_for_employee.rb
  app/data_migrations/update_fields_of_employee_role.rb
  lib/tasks/update_employer_profile_id_for_employee.rake
  lib/tasks/update_fields_of_employee_role.rake
  spec/data_migrations/update_employer_profile_id_for_employee_spec.rb
  spec/data_migrations/update_fields_of_employee_role_spec.rb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Critical Data

#1365 26677: TerminationOfMaHealthLinkParticipation
  app/data_migrations/update_subject_for_messages.rb
  lib/tasks/update_subject_for_messages.rake
  spec/data_migrations/update_subject_for_messages_spec.rb
Labels: Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1414 25592: Employers-Source Kind box is too large
  app/assets/stylesheets/ui-components/mahc-theme.scss
  app/views/exchanges/hbx_profiles/_invoice.html.slim
Labels: Mergeable: No, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1428 27300: FEIN Correction: Rigali Roofing
  app/data_migrations/components/fix_organization.rb
  lib/tasks/migrations/components/fix_organization.rake
  spec/data_migrations/components/fix_organization_spec.rb
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Critical Data

#1434 27239: Should be able to trigger the notice by taking input FEIN and event name
  app/data_migrations/upload_notice_to_employer_account.rb
  lib/tasks/notices/upload_notice_to_employer_account.rake
  spec/data_migrations/upload_notice_to_employer_account_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1437 29186: 10/1 ER Configuration Update
  config/settings.yml
Labels: Mergeable: Yes, Priority: High, Status: Pending Deployment, Tracker: Hot Fix

#1436 28504: Benefits Package Missing 4th Rating Tier on Benefits tab
  app/assets/stylesheets/employer.scss.erb
  app/assets/stylesheets/new.scss.erb
  components/sponsored_benefits/app/assets/stylesheets/new.scss
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Bug

#1453 29792: Revert OE Start_on Configuration Change
  config/settings.yml
Labels: Mergeable: Yes, Priority: Immediate, Status: Stakeholder Review, Tracker: Critical Data

#1458 29691: Unable to Shop For Renewal Coverage - undefined method `sponsored_benefit_for' for nil:NilClass
  app/data_migrations/update_predecessor_id_on_bp.rb
  lib/tasks/migrations/update_predecessor_id_on_bp.rake
  spec/data_migrations/update_predecessor_id_on_bp_spec.rb
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Bug
