Repository health-connector/enroll, pull requests merged in 2018-05, with the labels that each got.

#1209 24303: Production Rates don't match calculator values
  app/models/plan_cost_decorator.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Hot Fix

#1228 24467: Immigration status doc field labels
  app/views/insured/consumer_roles/docs_shared/_citizenship_number.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1200 24188: ER Roster Report broken due to DC/MA code merge
  lib/tasks/hbx_reports/employer_roster_report.rake
Labels: Mergeable: Yes, Priority: Urgent, Status: Pending Deployment, Tracker: Bug

#1231 24523: Shift ER Shopping Start_Date to 5/23
  config/settings.yml
  features/employers/add_plan_year_for_employer.feature
Labels: Mergeable: No, Priority: Urgent, Status: Accepted Pending Release, Tracker: Support

#1241 24664: Admin Notice Tab Issue
  app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Bug

#1240 24083: Revert ER Shopping date Change
  config/cucumber.yml
  config/settings.yml
  features/employers/add_plan_year_for_employer.feature
  features/employers/cobra.feature
  features/employers/cobra_sole_source.feature
  features/employers/employer_attestation.feature
  features/employers/employer_attestation_sole_source.feature
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Support
