Repository health-connector/enroll, pull requests merged in 2018-11, with the labels that each got.

#1493 36974: GLOBAL FIX: Rehired EE Unable to Link to ER
  app/models/census_employee.rb
  spec/models/census_employee_spec.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1513 37863: EDI Automation date deadline changes due to holiday schedule
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Data

#1514 37558: Dental - 2/1 Conversion Data
  components/benefit_sponsors/app/models/benefit_sponsors/importers/conversion_employee_policy_action.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Data
