Repository health-connector/enroll, pull requests merged in 2018-02, with the labels that each got.

#963 21786: Admin: Family tab - New Employee Paper Application link - 'We're sorry, but something went wrong.' issue
  app/controllers/insured/employee_roles_controller.rb
Labels: Priority: Urgent, Status: Promote to Test Environment, Tracker: App-Dev_Use Case

#968 22100: Settings Update: OE_Start on System Setting Change
  config/settings.yml
  spec/models/plan_year_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Support

#962 22083: BQT - One Plan Quote won't save
  components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js
Labels: Mergeable: Yes, Priority: Normal, Status: Pending Deployment, Tracker: Bug

#946 21784: ERs did not renew
  app/data_migrations/change_er_to_applicant_state.rb
  lib/tasks/change_er_to_applicant_state.rake
  spec/data_migrations/change_er_to_applicant_state_spec.rb
Labels: Priority: Urgent, Status: Accepted Pending Release, Tracker: Data

#899 18202: ER Portal - Add/Edit Plan Year Page - Text Correction Needed for earliest PY start date
  app/views/shared/_plan_year_fields.html.erb
Labels: Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#982 22308: Endpoints defined in 18811 reference incorrect endpoints
  components/transport_profiles/app/models/transport_profiles/processes/legacy/transfer_payment_processor_reports.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Pending Deployment, Tracker: Hot Fix

#985 22201: Link Broker Account to HBX ID 101802
  lib/tasks/datafix_update_broker_role_to_exisiting_user.rake
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Hot Fix
