Repository health-connector/enroll, pull requests merged in 2018-06, with the labels that each got.

#1223 24044: Employer Quoting Tool "Copy Quote" Not Working
  app/models/benefit_group.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#1238 24066: BQT - Cannot Save Quote
  components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/plan_design_proposals.js
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#1213 24002: Inconsistencies with multiple benefit groups in MA
  app/controllers/employers/plan_years_controller.rb
  app/views/employers/plan_years/calc_offered_plan_contributions.js.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1244 24771: Add Open Enrollment Start/End and Carrier and Plan Selection to Outstanding Monthly Enrollment Reports
  lib/tasks/hbx_reports/outstanding_monthly_enrollments.rake
Labels: Mergeable: Yes, Priority: Normal, Status: Stakeholder Review, Tracker: Data

#1214 24359: Turn On Manual Term/Cancel for Admin
  app/models/effective/datatables/family_data_table.rb
  features/step_definitions/admin_pundit_authorization_steps.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Code Refactor

#1264 25117: Corrected Fallon PBT
  lib/object_builders/qhp_builder.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Enhancement

#1274 25482: need to include `include Notifier::ApplicationHelper` in notice_builder.rb
  components/notifier/app/models/notifier/notice_builder.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1257 25058: Turn On SEP Dashboard
  app/models/effective/datatables/family_data_table.rb
  features/step_definitions/admin_pundit_authorization_steps.rb
  features/step_definitions/integration_steps.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1276 25495: Missing "Bulk Action" Button on the Roster
  app/views/employers/employer_profiles/my_account/_employees_by_status.html.erb
  features/employers/roster.feature
  features/step_definitions/employers_steps.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1277 25277: Employee - Enrolling - View Privacy Act Statement link - Error
  app/helpers/config/site_helper.rb
  app/views/insured/employee_roles/privacy.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: User Story

#1285 25427: MA Broker Approved but no Magic URL
  app/data_migrations/broker_email_invitation.rb
  app/data_migrations/cancel_plan_year.rb
  lib/tasks/cancel_plan_year.rake
  spec/data_migrations/cancel_plan_year_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Pending Deployment, Tracker: Bug
