Repository health-connector/enroll, pull requests merged in 2018-12, with the labels that each got.

#1545 38837: Dental Enrollments Not Showing on New Sale Invoices
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1546 38842: Removal of Invoices
  app/data_migrations/delete_single_invoice_with_fein.rb
  spec/data_migrations/delete_single_invoice_with_fein_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Code Refactor

#1553 38658: Employer Data Extract
  lib/tasks/export_employers.rake
Labels: Priority: Immediate, Status: Accepted Pending Release, Tracker: Code Refactor
