Repository health-connector/enroll, pull requests merged in 2018-03, with the labels that each got.

#989 22298: BQT - Quote Download Link not working on Published Quote page
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/shared/_pdp_plan_details.html.erb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/show.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1004 22499: View SBC link on quotes does not work
  app/views/shared/plan_shoppings/_sbc_link.html.erb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/shared/_pdp_plan_details.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1009 22447: Sort commission statements within year in descending order (newest first)
  app/controllers/broker_agencies/profiles_controller.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1040 23100: When Zip code is entered it shows the "Zip code outside of DC" text
  app/helpers/config/aca_helper.rb
  app/views/shared/_office_location_fields.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1042 23152: Calendar
  app/helpers/config/aca_helper.rb
  app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1046 23145: Employee Paper Application Link from Family page
  app/helpers/config/aca_helper.rb
  app/models/concerns/config/aca_model_concern.rb
  app/views/exchanges/hbx_profiles/_family_index_datatable.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1049 23153: Recaptcha
  app/controllers/users/sessions_controller.rb
  app/helpers/config/aca_helper.rb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/settings.yml
Labels: Mergeable: No, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1024 22876: MASSACHUSETTS Upload Termination Notice to Employer Secured Message Inbox in EA- March 2018
  app/data_migrations/upload_notice_to_employer_account.rb
  lib/tasks/upload_notice_for_employers.rake
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Critical Data

#1054 23147: Employer Attestation
  app/helpers/config/aca_helper.rb
  app/models/concerns/config/aca_model_concern.rb
  app/models/effective/datatables/employer_datatable.rb
  app/models/plan_year.rb
  app/views/employers/employer_profiles/my_account/_documents.html.erb
  app/views/employers/plan_years/_publish_modal.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1055 23153: Recaptcha
  app/controllers/concerns/recaptcha_concern.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1058 23147: Employer Attestation
  app/models/effective/datatables/employer_datatable.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1059 23305: Plan Year - "We are sorry message" in ER, EE and IVL Flows
  app/controllers/employers/plan_years_controller.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1057 23150: Security Questions
  app/views/people/landing_pages/_personal.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1062 23099: SIC link is displayed while creating the Employer
  app/views/shared/_employer_profile_fields.html.erb
  app/views/shared/organizations/_entity_name_and_type_fields_autofill.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1068 23305: Plan Year - "We are sorry message" in ER, EE and IVL Flows
  app/helpers/config/aca_helper.rb
  app/views/insured/plan_shoppings/show.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1069 23382: Update DC application dead line to take DC settings.
  app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb
  app/views/employers/plan_years/_recommend_dates.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1071 23382: Update DC application dead line to take DC settings.
  app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb
  db/seedfiles/translations/en/employer.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1073 23339: should disable all MA flash messages and notices template as well.
  app/controllers/users/registrations_controller.rb
  app/helpers/portal_header_helper.rb
  config/locales/devise.en.yml
  db/seedfiles/translations/en/welcome_index.rb
  features/step_definitions/security_question_step.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/plan_year_spec.rb
  spec/notices/shop_employer_notices/initial_employer_denial_notice_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Promote to Test Environment, Tracker: Code Refactor

#1044 23140: Create a report to compare SHOP anniversary EA enrollments with EDI outbound
  lib/tasks/hbx_reports/outstanding_monthly_enrollments.rake
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Enhancement

#1067 23306: Admin - Broker Agency - "Assign" tab and "Quoting Tool" tabs are missing
  app/views/broker_agencies/profiles/_menu.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1083 23467: Broker account page - "Brokers", "Agency Mail" links should be disabled
  app/views/broker_agencies/profiles/_menu.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1084 23494: Cancel/terminate enrollment buttons should be enabled
  app/models/effective/datatables/family_data_table.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1077 23299: Employee Plan shopping page HTML issues
  app/views/insured/families/_apply_for_medicaid_widget.html.erb
Labels: Mergeable: No, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1091 23495: "View Username and Email" button does not work for admin
  app/models/effective/datatables/employer_datatable.rb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/broker_agency_profiles/_employers.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1090 23339: should disable all MA flash messages and notices template as well.
  app/helpers/config/site_helper.rb
  app/mailers/application_mailer.rb
  app/mailers/user_mailer.rb
  app/views/notices/shop_employee_notices/13_employee_open_enrollment_reminder.html.erb
  app/views/notices/shop_employee_notices/15_employee_select_plan_during_annual_open_enrollment.html.erb
  app/views/notices/shop_employer_notices/2_initial_employer_approval_notice.html.erb
  app/views/user_mailer/broker_application_confirmation.html.erb
  app/views/user_mailer/broker_invitation_email.html.erb
  app/views/user_mailer/broker_pending_completed_training_missing_carrier.html.erb
  app/views/user_mailer/broker_pending_missing_training_and_carrier.html.erb
  config/settings.yml
Labels: Mergeable: Yes, Priority: High, Status: Promote to Test Environment, Tracker: Code Refactor

#1074 23411: Include DC drop down options under Families Tab.
  app/views/exchanges/hbx_profiles/shared/_primary_nav.html.erb
Labels: Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1093 23467: Broker account page - "Brokers", "Agency Mail" links should be disabled
  app/views/broker_agencies/profiles/_menu.html.erb
Labels: Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#1102 23552: Fix Dev Seed for IVL Market 2018
  db/seedfiles/admins_seed.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor
