Repository health-connector/enroll, pull requests merged in 2019-05, with the labels that each got.

#1666 40592
  app/models/census_employee.rb
  spec/models/census_employee_spec.rb
Labels: Mergeable: No, Priority: 1-Immediate, Status: Pending Deployment, Tracker: Hot Fix

#1667 40549
  app/views/employers/census_employees/_form.html.erb
  app/views/ui-components/v1/navs/_employers_navigation.html.slim
  components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_primary_nav.html.erb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_families.html.erb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/show.html.erb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller_spec.rb
  components/benefit_sponsors/spec/dummy/app/views/ui-components/v1/navs/_employers_navigation.html.slim
  components/benefit_sponsors/spec/views/benefit_sponsors/profiles/employers/employer_profiles/show.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Pending Deployment, Tracker: Hot Fix

#1678 41802
  app/reports/hbx_reports/outstanding_monthly_enrollments.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1685 22903
  app/models/employer_attestation.rb
  app/models/employer_attestation_document.rb
  spec/models/employer_attestation_document_spec.rb
  spec/models/employer_attestation_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Pending Deployment, Tracker: Bug

#1665 41522
  app/data_migrations/change_enrollment_details.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Trading Partner Data

#1691 42046
  components/benefit_sponsors/app/models/benefit_sponsors/model_events/hbx_enrollment.rb
  components/benefit_sponsors/app/models/benefit_sponsors/observers/hbx_enrollment_observer.rb
  components/benefit_sponsors/spec/dummy/app/models/benefit_group_assignment.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/employee_coverage_termination_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/group_termination_notice_spec.rb
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Use Case

#1692 42167
  config/settings.yml
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support
