Repository health-connector/enroll, pull requests merged in 2019-04, with the labels that each got.

#1646 40516
  app/data_migrations/fix_title_for_existing_quotes.rb
  lib/tasks/migrations/fix_title_for_existing_quotes.rake
  spec/data_migrations/fix_title_for_existing_quotes_spec.rb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1607 39694
  app/models/census_employee.rb
  app/models/hbx_enrollment.rb
  app/views/employers/census_employees/show.html.erb
  app/views/shared/_census_employee_fields.html.erb
  app/views/shared/_past_enrollment.html.erb
  app/views/shared/_past_enrollments.html.erb
  spec/models/census_employee_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1672 41705
  config/settings.yml
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Support
