Repository health-connector/enroll, pull requests merged in 2019-03, with the labels that each got.

#1618 39820
  components/benefit_sponsors/app/models/benefit_sponsors/services/new_profile_registration_service.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/new_profile_registration_service_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1623 40277
  app/data_migrations/add_hbx_enrollment_member.rb
  lib/tasks/add_hbx_enrollment_member.rake
  spec/data_migrations/add_hbx_enrollment_member_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1641 40288
  app/assets/stylesheets/application.scss.erb
  app/views/ui-components/v1/navs/_header.html.slim
  config/settings.yml
  spec/views/ui-components/v1/layouts/_header.slim_spec.rb
Labels: Priority: Immediate, Status: Accepted Pending Release, Tracker: Support

#1652 40670
  app/views/events/phones/_phone.xml.haml
  spec/views/events/individuals/created.xml.haml_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#1516 36810
  app/data_migrations/fix_title_for_existing_quotes.rb
  lib/tasks/migrations/fix_title_for_existing_quotes.rake
  spec/data_migrations/fix_title_for_existing_quotes_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug
