Repository health-connector/enroll, pull requests merged in 2019-01, with the labels that each got.

#1561 38906: 1/1 renewal 13 RIVER STREET LLC
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Critical Data

#1577 39282
  lib/tasks/update_super_group_ids.rake
Labels: Assignee: Sri Harsha Poosa, Priority: Normal, Status: Functional Testing, Tracker: Feature

#1594 39422
  components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
  components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Support
