Repository health-connector/enroll, pull requests merged in 2020-04, with the labels that each got.

#1814 54740
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1820 43230
  app/data_migrations/change_census_employee_details.rb
  lib/tasks/change_census_employee_details.rake
  spec/data_migrations/change_census_employee_details_spec.rb
Labels: Assignee: Sri Harsha Poosa, Priority: 4-Normal, Status: Promote to UAT, Tracker: Bug

#1817 86484
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_employer_datatable.rb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1806 85245
  app/assets/javascripts/ui-components/forms.js.erb
  app/controllers/broker_agencies/profiles_controller.rb
  app/controllers/general_agencies/profiles_controller.rb
  app/data_migrations/delink_broker_general_agency.rb
  app/helpers/events_helper.rb
  app/javascript/benefit_sponsors/controllers/office_locations_controller.js
  app/models/broker_role.rb
  app/models/person.rb
  app/views/events/v2/phones/_phone.xml.haml
  app/views/ui-components/v1/forms/office_locations/_old_style_address.html.erb
  app/views/ui-components/v1/forms/office_locations/_phone.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/shared/_office_location_fields.html.erb
  components/benefit_sponsors/db/seedfiles/cca/fixtures/issuer_profile_210004.yaml
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/registrations_controller_spec.rb
  components/benefit_sponsors/spec/dummy/app/models/broker_role.rb
  components/benefit_sponsors/spec/dummy/app/models/person.rb
  components/benefit_sponsors/spec/dummy/app/models/phone.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/office_location_form_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/profile_form_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/registration_form_spec.rb
  components/old_sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_organizations_controller_spec.rb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/office_locations/_office_location_fields.html.erb
  components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_organizations_controller_spec.rb
  db/seedfiles/cca/fixtures/issuer_profile_210004.yaml
  features/brokers/broker_registration.feature
  features/step_definitions/cca_sole_source_benefit_package_steps.rb
  features/step_definitions/integration_steps.rb
  features/step_definitions/manage_family.rb
  features/support/worlds/census_employee_world.rb
  lib/tasks/hbx_reports/employer_changes.rake
  lib/tasks/migrations/add_phones_to_people.rake
  spec/controllers/broker_agencies/broker_roles_controller_spec.rb
  spec/controllers/broker_agencies/profiles_controller_spec.rb
  spec/controllers/general_agencies/profiles_controller_spec.rb
  spec/data_migrations/delink_broker_general_agency_spec.rb
  spec/models/broker_role_spec.rb
  spec/models/forms/broker_agency_profile_spec.rb
  spec/models/forms/general_agency_profile_spec.rb
  spec/views/employers/employer_profiles/_employer_broker_widget.html.erb_spec.rb
  spec/views/events/v2/organizations/_office_locations.haml_spec.rb
Labels: Priority: 4-Normal, Status: Peer Review, Tracker: Bug

#1803 33038
  app/views/ui-components/v1/navs/_employers_navigation.html.slim
  components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
  components/benefit_sponsors/app/models/benefit_sponsors/queries/broker_families_query.rb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_families.html.erb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/show.html.erb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller_spec.rb
  components/benefit_sponsors/spec/dummy/app/models/employee_role.rb
  components/benefit_sponsors/spec/dummy/app/models/employer_profile.rb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1786 42384
  app/data_migrations/change_enrollment_details.rb
  app/models/census_employee.rb
  app/models/hbx_enrollment.rb
  app/models/importers/transcripts/enrollment_actions.rb
  app/models/importers/transcripts/enrollment_transcript.rb
  app/models/parsers/xml/cv/importers/enrollment_parser.rb
  app/models/transcripts/base.rb
  app/models/transcripts/enrollment_common.rb
  app/models/transcripts/enrollment_transcript.rb
  lib/transcript_generator.rb
  spec/models/importers/transcripts/enrollment_transcript_spec.rb
  spec/models/parsers/xml/cv/importers/enrollment_parser_spec.rb
  spec/models/transcripts/enrollment_transcript_spec.rb
Labels: Priority: 2-Urgent, Status: Functional Testing, Tracker: Code Refactor

#1792 37906
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim
Labels: Assignee: Keeta James, Priority: 4-Normal, Status: Stakeholder Review, Tracker: Support

#1824 87250
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/accounts/_pay_my_bill.html.erb
Labels: Assignee: Sri Harsha Poosa, Priority: 2-Urgent, Status: Promote to Test Environment, Tracker: Support

#1813 86635
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_schedular.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_schedular_spec.rb
Labels: Assignee: Lavina Sauders, Priority: 4-Normal, Status: Stakeholder Review, Tracker: Bug

#1799 86503
  components/sponsored_benefits/app/controllers/sponsored_benefits/organizations/plan_design_organizations_controller.rb
  components/sponsored_benefits/app/models/sponsored_benefits/concerns/organization_concern.rb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/office_locations/_office_location_fields.html.erb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_organizations/_error_messages.html.erb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_organizations/edit.html.erb
  components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_organizations_controller_spec.rb
  components/sponsored_benefits/spec/dummy/app/models/benefit_group.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1794 85813
  app/helpers/float_helper.rb
  app/views/events/v2/employers/_benefit_group.xml.haml
  components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/contribution_level.rb
  components/benefit_sponsors/spec/dummy/app/helpers/float_helper.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/sponsored_benefits/contribution_level_spec.rb
  lib/v2_group_xml_generator.rb
  spec/helpers/float_helper_spec.rb
Labels: Priority: 4-Normal, Status: BA Review, Tracker: Data
