Repository health-connector/enroll, pull requests merged in 2020-10, with the labels that each got.

#1910 23896
  components/benefit_sponsors/app/models/effective/datatables/benefit_sponsors_coverage_reports_data_table.rb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1900 89544
  app/models/queries/shop_monthly_enrollments.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1907 39791
  components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller.rb
  components/benefit_sponsors/app/policies/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller_policy.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller_spec.rb
  components/benefit_sponsors/spec/policies/profiles/broker_agencies/broker_agency_profiles_controller_policy_spec.rb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1922 90659
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy_spec.rb
Labels: Priority: 2-Urgent, Status: Functional Testing, Tracker: Bug

#1912 90212
  components/benefit_markets/app/models/benefit_markets/products/product.rb
  components/benefit_markets/spec/models/benefit_markets/products/product_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#1921 90644
  app/models/services/plan_validation_report.rb
Labels: Assignee: Sheheryar Tariq, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Feature

#1920 90645
  app/models/services/plan_validation_report.rb
Labels: Assignee: Sheheryar Tariq, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Feature
