Repository health-connector/enroll, pull requests merged in 2020-05, with the labels that each got.

#1832 28794
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/observers/organization_observer_spec.rb
Labels: Priority: 4-Normal, Status: Functional Testing, Tracker: Bug

#1839 87491
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service.rb
  components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb
Labels: Assignee: Vishal Kalletla, Priority: 4-Normal, Status: Returned for Deficiency, Tracker: Bug

#1822 87130
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug
