Repository health-connector/enroll, pull requests merged in 2021-01, with the labels that each got.

#1940 87483
  components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_proposal.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1947 24043
  components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_datatable_concern.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#1949 88181
  components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/new.html.slim
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#1954 87449
  app/helpers/insured/families_helper.rb
  app/models/family.rb
  app/models/hbx_enrollment.rb
  app/views/insured/families/_enrollment.html.erb
  features/employee/employee_plan_shopping_make_changes_button_display.feature
  features/step_definitions/employers_steps.rb
  features/step_definitions/integration_steps.rb
  features/step_definitions/new_hire_steps.rb
  features/support/worlds/census_employee_world.rb
  spec/helpers/insured/families_helper_spec.rb
  spec/models/hbx_enrollment_spec.rb
  spec/views/employers/census_employees/show.html.erb_spec.rb
  spec/views/insured/families/_enrollment.html.erb_spec.rb
Labels: Assignee: Vishal Kalletla, Priority: 3-High, Status: Peer Review, Tracker: Bug

#1967 19238
  app/models/effective/datatables/employee_datatable.rb
Labels: Priority: 4-Normal, Status: Functional Testing, Tracker: Support

#1968 92311
  config/settings.yml
Labels: Assignee: Lavina Sauders, Priority: 4-Normal, Status: Stakeholder Review, Tracker: Support

#1978 92328
  app/assets/javascripts/glossary.js
  app/assets/stylesheets/ui-components/mahc-theme.scss
  app/models/products/qhp_deductible.rb
  app/views/layouts/application.html.erb
  app/views/ui-components/v1/cards/_metal_level_select.html.slim
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_sponsor_health_catalog_decorator.rb
  components/sponsored_benefits/app/assets/javascripts/sponsored_benefits/glossary.js
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/plans/_plan_search_fields.html.erb
  config/initializers/assets.rb
Labels: Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Feature
